# Input File
$InputFile = "C:\Temp\Servers.txt"

# Output File
$DateTime = Get-Date -Format "yyyyMMdd_HHmmss"
$UserName = $env:USERNAME
$OutputFile = "C:\Temp\AccessStatusReport_${DateTime}_${UserName}.html"

# Function - RDP Test
function Test-RDPAccess {
    param($ServerName)

    try {
        if (Test-NetConnection -ComputerName $ServerName -Port 3389 -InformationLevel Quiet -WarningAction SilentlyContinue) {
            return "Good"
        }
        else {
            return "Bad"
        }
    }
    catch {
        return "Bad"
    }
}

# Function - SQL Connectivity Test
function Test-SQLAccess {
    param($SqlServerName)

    try {
        $ConnString = "Server=$SqlServerName;Integrated Security=True;Connection Timeout=5"

        $Conn = New-Object System.Data.SqlClient.SqlConnection
        $Conn.ConnectionString = $ConnString
        $Conn.Open()
        $Conn.Close()

        return "Good"
    }
    catch {
        return "Bad"
    }
}

# Read File
$Results = foreach ($Line in Get-Content $InputFile)
{
    if ($Line.Trim() -eq "") { continue }

    $ServerName,$SQLServerName = $Line.Split(',')

    Write-Host "Checking $ServerName / $SQLServerName"

    [PSCustomObject]@{
        DateTime      = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        ServerName    = $ServerName.Trim()
        SQLServerName = $SQLServerName.Trim()
        RDPAccess     = Test-RDPAccess $ServerName.Trim()
        SQLAccess     = Test-SQLAccess $SQLServerName.Trim()
    }
}

# Create HTML
$HTML = @"
<html>
<head>
<title>Access Status Report</title>

<style>
body {font-family: Arial;}
table {border-collapse: collapse; width:100%;}
th {background:#4472C4;color:white;padding:8px;border:1px solid black;}
td {border:1px solid black;padding:6px;}

.good {
background:#C6EFCE;
color:#006100;
font-weight:bold;
}

.bad {
background:#FFC7CE;
color:#9C0006;
font-weight:bold;
}
</style>

</head>
<body>

<h2>Server Access Status Report</h2>

<p>
<b>Generated By:</b> $UserName<br>
<b>Generated On:</b> $(Get-Date)
</p>

<table>
<tr>
<th>DateTime</th>
<th>ServerName</th>
<th>SQLServerName</th>
<th>RDPAccess</th>
<th>SQLAccess</th>
</tr>
"@

foreach ($Row in $Results)
{
    $RDPClass = if ($Row.RDPAccess -eq "Good") { "good" } else { "bad" }
    $SQLClass = if ($Row.SQLAccess -eq "Good") { "good" } else { "bad" }

    $HTML += @"
<tr>
<td>$($Row.DateTime)</td>
<td>$($Row.ServerName)</td>
<td>$($Row.SQLServerName)</td>
<td class='$RDPClass'>$($Row.RDPAccess)</td>
<td class='$SQLClass'>$($Row.SQLAccess)</td>
</tr>
"@
}

$HTML += @"
</table>
</body>
</html>
"@

# Save Report
$HTML | Out-File $OutputFile -Encoding UTF8

Write-Host ""
Write-Host "Report Created:" -ForegroundColor Green
Write-Host $OutputFile -ForegroundColor Cyan

Invoke-Item $OutputFile
