# Input File
$InputFile = "C:\Temp\Servers.txt"

# Output File
$DateTime = Get-Date -Format "yyyyMMdd_HHmmss"
$UserName = $env:USERNAME
$OutputFile = "C:\Temp\AccessStatusReport_${DateTime}_${UserName}.html"

$Results = @()

# Read Input File
$Servers = Get-Content $InputFile

foreach ($Line in $Servers)
{
    $Values = $Line.Split(",")

    $ServerName = $Values[0].Trim()
    $SqlServerName = $Values[1].Trim()

    Write-Host "Checking $ServerName / $SqlServerName"

    # RDP Check
    try
    {
        $RDP = Test-NetConnection -ComputerName $ServerName -Port 3389 -InformationLevel Quiet

        if ($RDP)
        {
            $RDPStatus = "Good"
        }
        else
        {
            $RDPStatus = "Bad"
        }
    }
    catch
    {
        $RDPStatus = "Bad"
    }

    # SQL Check
    try
    {
        $SQL = Test-NetConnection -ComputerName $SqlServerName -Port 1433 -InformationLevel Quiet

        if ($SQL)
        {
            $SQLStatus = "Good"
        }
        else
        {
            $SQLStatus = "Bad"
        }
    }
    catch
    {
        $SQLStatus = "Bad"
    }

    $Results += [PSCustomObject]@{
        DateTime      = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        ServerName    = $ServerName
        SQLServerName = $SqlServerName
        RDPAccess     = $RDPStatus
        SQLAccess     = $SQLStatus
    }
}

# HTML Header
$HTML = @"
<html>
<head>
<title>Access Status Report</title>
<style>
body {
    font-family: Arial;
}

table {
    border-collapse: collapse;
    width: 100%;
}

th {
    background-color: #4472C4;
    color: white;
    padding: 8px;
}

td {
    border: 1px solid black;
    padding: 6px;
    text-align: center;
}

.good {
    background-color: #C6EFCE;
    color: #006100;
    font-weight: bold;
}

.bad {
    background-color: #FFC7CE;
    color: #9C0006;
    font-weight: bold;
}
</style>
</head>
<body>

<h2>Server Access Status Report</h2>
<h4>Generated By : $UserName</h4>
<h4>Generated On : $(Get-Date)</h4>

<table>
<tr>
<th>DateTime</th>
<th>Server Name</th>
<th>SQL Server Name</th>
<th>RDP Access</th>
<th>SQL Access</th>
</tr>
"@

foreach ($Result in $Results)
{
    $RDPClass = if ($Result.RDPAccess -eq "Good") { "good" } else { "bad" }
    $SQLClass = if ($Result.SQLAccess -eq "Good") { "good" } else { "bad" }

    $HTML += @"
<tr>
<td>$($Result.DateTime)</td>
<td>$($Result.ServerName)</td>
<td>$($Result.SQLServerName)</td>
<td class='$RDPClass'>$($Result.RDPAccess)</td>
<td class='$SQLClass'>$($Result.SQLAccess)</td>
</tr>
"@
}

$HTML += @"
</table>
</body>
</html>
"@

$HTML | Out-File $OutputFile -Encoding UTF8

Write-Host ""
Write-Host "Report Generated:"
Write-Host $OutputFile -ForegroundColor Green

# Open Report
Invoke-Item $OutputFile
