###############################################################################
# Server & SQL Access Validation Report
#
# Input File Format:
# ServerName,SQLServerName
# APP01,SQL01
# APP02,SQL02\REPORTING
# APP03,SQL03\DBSERVICES
#
# Output:
# AccessStatusReport_<DateTime>_<Username>.html
#
# Prerequisite:
# Install-Module SqlServer -Scope CurrentUser -Force
###############################################################################

Import-Module SqlServer -ErrorAction Stop

#----------------------------------------------------------------------------
# INPUT FILE
#----------------------------------------------------------------------------
$InputFile = "C:\Temp\Servers.txt"

#----------------------------------------------------------------------------
# OUTPUT FILE
#----------------------------------------------------------------------------
$DateTime = Get-Date -Format "yyyyMMdd_HHmmss"
$UserName = $env:USERNAME

$OutputFile = Join-Path `
    (Split-Path $InputFile -Parent) `
    "AccessStatusReport_${DateTime}_${UserName}.html"

#----------------------------------------------------------------------------
# RDP ACCESS CHECK
#----------------------------------------------------------------------------
function Test-RDPAccess {
    param (
        [string]$ServerName
    )

    try {
        $Result = Test-NetConnection `
                    -ComputerName $ServerName `
                    -Port 3389 `
                    -InformationLevel Quiet `
                    -WarningAction SilentlyContinue

        if ($Result) {
            return "Good"
        }
        else {
            return "Bad"
        }
    }
    catch {
        return "Bad"
    }
}

#----------------------------------------------------------------------------
# SQL ACCESS CHECK
#----------------------------------------------------------------------------
function Test-SQLAccess {
    param (
        [string]$SqlServerName
    )

    try {

        Invoke-Sqlcmd `
            -ServerInstance $SqlServerName `
            -Query "SELECT @@SERVERNAME AS ServerName" `
            -QueryTimeout 10 `
            -TrustServerCertificate `
            -ErrorAction Stop | Out-Null

        return @{
            Status  = "Good"
            Details = "Connected"
        }
    }
    catch {

        return @{
            Status  = "Bad"
            Details = $_.Exception.Message
        }
    }
}

#----------------------------------------------------------------------------
# READ INPUT FILE
#----------------------------------------------------------------------------
$ServerList = Get-Content $InputFile |
              Where-Object {
                    $_.Trim() -ne "" -and
                    $_ -match ","
              }

$Results = @()

foreach ($Line in $ServerList) {

    $Values = $Line.Split(",")

    $ServerName    = $Values[0].Trim()
    $SqlServerName = $Values[1].Trim()

    Write-Host "Checking Server: $ServerName | SQL: $SqlServerName" -ForegroundColor Yellow

    # RDP Check
    $RDPStatus = Test-RDPAccess $ServerName

    # SQL Check
    $SQLResult = Test-SQLAccess $SqlServerName

    $Results += [PSCustomObject]@{
        DateTime      = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        ServerName    = $ServerName
        SQLServerName = $SqlServerName
        RDPAccess     = $RDPStatus
        SQLAccess     = $SQLResult.Status
        Details       = $SQLResult.Details
    }
}

#----------------------------------------------------------------------------
# HTML HEADER
#----------------------------------------------------------------------------
$HTML = @"
<html>
<head>
<title>Server Access Status Report</title>

<style>

body{
    font-family: Arial;
    margin:20px;
}

h2{
    color:#2F5597;
}

table{
    border-collapse: collapse;
    width:100%;
}

th{
    background-color:#4472C4;
    color:white;
    border:1px solid black;
    padding:8px;
    text-align:center;
}

td{
    border:1px solid black;
    padding:6px;
}

.good{
    background-color:#C6EFCE;
    color:#006100;
    font-weight:bold;
    text-align:center;
}

.bad{
    background-color:#FFC7CE;
    color:#9C0006;
    font-weight:bold;
    text-align:center;
}

</style>
</head>

<body>

<h2>Server & SQL Access Status Report</h2>

<p>
<b>Generated By:</b> $UserName <br>
<b>Generated On:</b> $(Get-Date)
</p>

<table>
<tr>
<th>Date Time</th>
<th>Server Name</th>
<th>SQL Server Name</th>
<th>RDP Access</th>
<th>SQL Access</th>
<th>Details</th>
</tr>
"@

#----------------------------------------------------------------------------
# BUILD HTML ROWS
#----------------------------------------------------------------------------
foreach ($Result in $Results) {

    $RDPClass = if ($Result.RDPAccess -eq "Good") { "good" } else { "bad" }
    $SQLClass = if ($Result.SQLAccess -eq "Good") { "good" } else { "bad" }

    $HTML += @"
<tr>
<td>$($Result.DateTime)</td>
<td>$($Result.ServerName)</td>
<td>$($Result.SQLServerName)</td>
<td class="$RDPClass">$($Result.RDPAccess)</td>
<td class="$SQLClass">$($Result.SQLAccess)</td>
<td>$($Result.Details)</td>
</tr>
"@
}

#----------------------------------------------------------------------------
# HTML FOOTER
#----------------------------------------------------------------------------
$HTML += @"
</table>
</body>
</html>
"@

#----------------------------------------------------------------------------
# GENERATE REPORT
#--------------------------
